using Amigo.Tenant.Commands.Common;
using MediatR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Amigo.Tenant.Commands.FileRepository
{
    public class FileRepositoryRegisterCommand: AuditBaseCommand, IAsyncRequest<CommandResult>
    {
        public string EntityCode { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public byte[] UtMediaFile { get; set; }
        public string ContentType { get; set; }
        public string FileExtension { get; set; }
        public bool? IsAutogenerated { get; set; }
        public bool? RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string AdditionalInfo { get; set; }
    }
}
