using System.Data.Entity.ModelConfiguration;
using Amigo.Tenant.CommandModel.Models;

namespace Amigo.Tenant.Infrastructure.Persistence.EF.Context.Mapping
{
    public class FileRepositoryMap : EntityTypeConfiguration<FileRepository>
    {
        public FileRepositoryMap()
        {
            // Primary Key
            this.HasKey(t => t.FileRepositoryId);
            // Table & Column Mappings
            this.ToTable("FileRepository");
            this.Property(t=> t.FileRepositoryId).HasColumnName("FileRepositoryId");
            this.Property(t=> t.EntityCode).HasColumnName("EntityCode");
            this.Property(t=> t.Name).HasColumnName("Name");
            this.Property(t=> t.ContentType).HasColumnName("ContentType");
            this.Property(t=> t.FileExtension).HasColumnName("FileExtension");
            this.Property(t=> t.utMediaFile).HasColumnName("utMediaFile");
            this.Property(t=> t.AdditionalInfo).HasColumnName("AdditionalInfo");
            this.Property(t=> t.IsAutogenerated).HasColumnName("IsAutogenerated");
            this.Property(t=> t.RowStatus          ).HasColumnName("RowStatus");
            this.Property(t=> t.CreatedBy          ).HasColumnName("CreatedBy");
            this.Property(t=> t.CreationDate       ).HasColumnName("CreationDate");
            this.Property(t => t.UpdatedBy         ).HasColumnName("UpdatedBy");
            this.Property(t => t.UpdatedDate).HasColumnName("UpdatedDate");

        }
}
}
