namespace Amigo.Tenant.CommandModel.Models
{
    using Abstract;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("FileRepository")]
    public partial class FileRepository : EntityBase
    {
        public int? FileRepositoryId { get; set; }
        public string EntityCode { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public string FileExtension { get; set; }
        public byte[] utMediaFile { get; set; }
        public string AdditionalInfo { get; set; }
        public bool? RowStatus { get; set; }
        public bool? IsAutogenerated { get; set; }
    }
}
