using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Amigo.Tenant.Application.DTOs.Responses.FileRepository
{
    public class FileRepositoryBase
    {
        public int FileRepositoryId { get; set; }
        public string EntityCode { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public string FileExtension { get; set; }
        public string AdditionalInfo { get; set; }
        public bool IsAutogenerated { get; set; }

    }
}
